//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myMpxjLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>create|/api/x_126085_umppmgr/uweb/create</string>
  <string>read|/api/x_126085_umppmgr/uweb/read/{0}</string>
  <string>update|/api/x_126085_umppmgr/uweb/update/1</string>
  <string>validate|/api/x_126085_umppmgr/uweb/uvaliduser/{0}</string>
  <string>lulists|/api/x_126085_umppmgr/uweb/lulist/1</string>
  <string>projlist|/api/x_126085_umppmgr/uweb/projlist/1</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection webService {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["webService"]));
            }
        }
    }
}
