// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace myMpxjLib.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using myMpxjLib;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class templateWebPage : templateWebPageBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(" \r\n");
            
            #line 8 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"

Action<List<mpxWrapper.SnowTask>,int,int,bool>
uEachTask = null; // null to avoid compile-time error
uEachTask  = delegate(List<mpxWrapper.SnowTask> argTaskList, int argLvlOrder, int argTreeDepth, bool argIsMpp)
{
    int myColSpan = argTreeDepth-argLvlOrder;
    int myDivMtCount = 7-argLvlOrder;
    foreach(mpxWrapper.SnowTask task in argTaskList)
    {

            
            #line default
            #line hidden
            this.Write("        <tr level=\"");
            
            #line 18 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(argLvlOrder));
            
            #line default
            #line hidden
            this.Write("\">\r\n");
            
            #line 19 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
	    for (int i=0;i<argLvlOrder;i++) { 
            
            #line default
            #line hidden
            this.Write("              <td style=\"background:transparent;min-width:14px;\">&nbsp;</td>\r\n");
            
            #line 21 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
		} 
            
            #line default
            #line hidden
            
            #line 22 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
		if (task.ChildTasks.Count>0) { 
            
            #line default
            #line hidden
            this.Write(" \r\n              <td class=\"divBtnExpCol\" style=\"background:transparent;min-width" +
                    ":14px;\">\r\n                <span class=\"glyphicon glyphicon-plus\"></span>\r\n      " +
                    "        </td>\r\n");
            
            #line 26 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t  <td style=\"background:transparent;min-width:14px;\">&nbsp;</td>\r\n");
            
            #line 28 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
      } 
            
            #line default
            #line hidden
            this.Write("              <td colspan=\"");
            
            #line 29 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(myColSpan));
            
            #line default
            #line hidden
            this.Write("\">\r\n                <div class=\"divTable mb\">\r\n                  <div class=\"divT" +
                    "head\" >\r\n                    <div class=\"divTr\">");
            
            #line 32 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 if (!argIsMpp) { 
            
            #line default
            #line hidden
            this.Write(" \r\n                      <div class=\"divTh tdTaskNum\">Task</div>");
            
            #line 33 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"                      <div class=""divTh tdTaskName"">Name</div>
                      <div class=""divTh tdTaskAssignmentGroup"">Assignment Grp</div>
                      <div class=""divTh tdTaskAssignedTo"">Assigned To</div>
                      <div class=""divTh tdTaskState"">State</div>
                      <div class=""divTh tdTaskPriority"">Priority</div>
                      <div class=""divTh tdTaskImpact"">Impact</div>
                      <div class=""divTh tdTaskType"">Task Type</div>
                      <div class=""divTh tdTaskConstraint"">Time Constraint</div>
                      <div class=""divTh tdTaskKeyMilestone"">Key Milestone</div>
                      <div class=""divTh tdTaskMilestone"">Milestone</div>
                      <div class=""divTh tdTaskPlannedStartDate "">Planned Start Date</div>
                      <div class=""divTh tdTaskPlannedEndDate"">Planned End Date</div>
                      <div class=""divTh tdTaskActualStartDate"">Actual Start Date</div>
                      <div class=""divTh tdTaskActualEndDate"">Actual End Date</div>
");
            
            #line 48 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
		for (int i=0;i<myDivMtCount;i++) { 
            
            #line default
            #line hidden
            this.Write("                      <div class=\"divTdMt\">&nbsp</div>\r\n");
            
            #line 50 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
      } 
            
            #line default
            #line hidden
            this.Write("                    </div>\r\n                  </div>\r\n                  <div clas" +
                    "s=\"divTbody\">\r\n                    <div class=\"divTr\">");
            
            #line 54 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 if (!argIsMpp) { 
            
            #line default
            #line hidden
            this.Write(" \r\n                      <div class=\"divTd bgWhite tdTaskNum fieldReadOnly\" statu" +
                    "s=\"");
            
            #line 55 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.TaskNum().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n\t\t\t\t\t\t<div class=\"divTd\" style=\"border:none;\" value=\"");
            
            #line 56 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.TaskNum().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 56 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.TaskNum().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n\t\t\t\t\t  </div> ");
            
            #line 57 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                      <div class=\"divTd bgWhite tdTaskName bgWhite\" status=\"");
            
            #line 58 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.TaskName().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 61 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.TaskName().value));
            
            #line default
            #line hidden
            this.Write("\" >");
            
            #line 61 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.TaskName().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                            <div class=""divTdRight btnLu"">
                              <span class=""glyphicon glyphicon-edit""></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class=""divTd bgWhite tdTaskAssignmentGroup"" status=""");
            
            #line 68 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.AssignmentGroup().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 71 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.AssignmentGroup().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 71 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.AssignmentGroup().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                            <div class=""divTdRight btnLu"">
                              <span class=""glyphicon glyphicon-search""></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class=""divTd bgWhite tdTaskAssignedTo");
            
            #line 78 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((task.AssignmentGroup().datastatus != "empty" && task.AssignedTo().value != "") ? "" : " fieldReadOnly"));
            
            #line default
            #line hidden
            this.Write("\" status=\"");
            
            #line 78 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.AssignedTo().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 81 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.AssignedTo().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 81 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.AssignedTo().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n \t\t\t\t\t\t    <div class=\"divTdRight btnLu\" ");
            
            #line 82 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((task.AssignmentGroup().datastatus != "empty" && task.AssignedTo().value != "") ? "":"style=display:none;"));
            
            #line default
            #line hidden
            this.Write(">\r\n\t\t\t\t\t\t\t  <span class=\"glyphicon glyphicon-search\"></span>\r\n\t\t\t\t\t\t    </div>\r\n " +
                    "                         </div>\r\n                        </div>\r\n               " +
                    "       </div>\r\n                      <div class=\"divTd bgWhite tdTaskState");
            
            #line 88 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && task.IsRollUp().value == "1")? " fieldReadOnly" : ""));
            
            #line default
            #line hidden
            this.Write("\" status=\"");
            
            #line 88 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.State().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 91 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.State().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 91 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.State().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n                            <div class=\"divTdRight btnLu\" ");
            
            #line 92 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && task.IsRollUp().value == "1")? "style=display:none;" : ""));
            
            #line default
            #line hidden
            this.Write(@">
                              <span class=""glyphicon glyphicon-search""></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class=""divTd bgWhite tdTaskPriority"" status=""");
            
            #line 98 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.Priority().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 101 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.Priority().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 101 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.Priority().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                            <div class=""divTdRight btnLu"">
                              <span class=""glyphicon glyphicon-search""></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class=""divTd bgWhite tdTaskImpact"" status=""");
            
            #line 108 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.Impact().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 111 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.Impact().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 111 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.Impact().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                            <div class=""divTdRight btnLu"">
                              <span class=""glyphicon glyphicon-search""></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class=""divTd bgWhite tdTaskType"" status=""");
            
            #line 118 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.TaskType().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 121 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.TaskType().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 121 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.TaskType().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                            <div class=""divTdRight btnLu"">
                              <span class=""glyphicon glyphicon-search""></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class=""divTd bgWhite tdTaskConstraint"" status=""");
            
            #line 128 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.Constraint().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 131 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.Constraint().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 131 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.Constraint().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                            <div class=""divTdRight btnLu"">
                              <span class=""glyphicon glyphicon-search""></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class=""divTd bgWhite tdTaskKeyMilestone"" status=""");
            
            #line 138 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.KeyMilestone().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 141 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.KeyMilestone().value!=""?task.KeyMilestone().value: "0"));
            
            #line default
            #line hidden
            this.Write("\">\r\n");
            
            #line 142 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 if (task.KeyMilestone().value=="1") { 
            
            #line default
            #line hidden
            this.Write("                              <span class=\"glyphicon glyphicon-ok\"></span>\r\n");
            
            #line 143 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                              <span class=\"glyphicon glyphicon-ban-circle\"></span" +
                    ">");
            
            #line 143 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 }; 
            
            #line default
            #line hidden
            this.Write(@"							</div>
				            <div class=""divTdRight btnLu"">
                              <span class=""glyphicon glyphicon-edit""></span>
                            </div>
                          </div>
                        </div>
                      </div>
					  <div class=""divTd bgWhite tdTaskMilestone"" status=""");
            
            #line 151 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.Milestone().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 154 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.Milestone().value!=""?task.Milestone().value: "0"));
            
            #line default
            #line hidden
            this.Write("\">\r\n");
            
            #line 155 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 if (task.Milestone().value=="1") { 
            
            #line default
            #line hidden
            this.Write("                              <span class=\"glyphicon glyphicon-ok\"></span>\r\n");
            
            #line 156 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                              <span class=\"glyphicon glyphicon-ban-circle\"></span" +
                    ">");
            
            #line 156 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 }; 
            
            #line default
            #line hidden
            this.Write(@"							</div>
							<div class=""divTdRight btnLu"">
                              <span class=""glyphicon glyphicon-edit""></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class=""divTd bgWhite tdTaskPlannedStartDate");
            
            #line 164 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && task.IsRollUp().value == "1")? " fieldReadOnly" : ""));
            
            #line default
            #line hidden
            this.Write("\" status=\"");
            
            #line 164 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.PlannedStartDate().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr dtmDiv\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 167 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.PlannedStartDate().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 167 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.PlannedStartDate().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n \t\t\t\t\t\t    <div class=\"divTdRight btnLu\" ");
            
            #line 168 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && task.IsRollUp().value == "1")? "style=display:none;" : ""));
            
            #line default
            #line hidden
            this.Write(">\r\n\t\t\t\t\t\t\t  <span class=\"glyphicon glyphicon-calendar\"></span>\r\n\t\t\t\t\t\t    </div>\r" +
                    "\n                          </div>\r\n                        </div>\r\n             " +
                    "         </div>\r\n                      <div class=\"divTd bgWhite tdTaskPlannedEn" +
                    "dDate");
            
            #line 174 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && task.IsRollUp().value == "1")? " fieldReadOnly" : ""));
            
            #line default
            #line hidden
            this.Write("\" status=\"");
            
            #line 174 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.PlannedEndDate().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr dtmDiv\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 177 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.PlannedEndDate().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 177 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.PlannedEndDate().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n \t\t\t\t\t\t    <div class=\"divTdRight btnLu\" ");
            
            #line 178 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && task.IsRollUp().value == "1")? "style=display:none;" : ""));
            
            #line default
            #line hidden
            this.Write(">\r\n\t\t\t\t\t\t\t  <span class=\"glyphicon glyphicon-calendar\"></span>\r\n\t\t\t\t\t\t    </div>\r" +
                    "\n                          </div>\r\n                        </div>\r\n             " +
                    "         </div>\r\n                      <div class=\"divTd bgWhite tdTaskActualSta" +
                    "rtDate");
            
            #line 184 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && task.IsRollUp().value == "1")? " fieldReadOnly" : ""));
            
            #line default
            #line hidden
            this.Write("\" status=\"");
            
            #line 184 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.ActualStartDate().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr dtmDiv\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 187 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.ActualStartDate().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 187 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.ActualStartDate().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n \t\t\t\t\t\t    <div class=\"divTdRight btnLu\" ");
            
            #line 188 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && task.IsRollUp().value == "1")? "style=display:none;" : ""));
            
            #line default
            #line hidden
            this.Write(">\r\n\t\t\t\t\t\t\t  <span class=\"glyphicon glyphicon-calendar\"></span>\r\n\t\t\t\t\t\t    </div>\r" +
                    "\n                          </div>\r\n                        </div>\r\n             " +
                    "         </div>\r\n                      <div class=\"divTd bgWhite tdTaskActualEnd" +
                    "Date");
            
            #line 194 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && task.IsRollUp().value == "1")? " fieldReadOnly" : ""));
            
            #line default
            #line hidden
            this.Write("\" status=\"");
            
            #line 194 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.ActualEndDate().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n                        <div class=\"divTable mt\">\r\n                          " +
                    "<div class=\"divTr dtmDiv\">\r\n\t\t\t\t\t\t\t<div class=\"divTd\" value=\"");
            
            #line 197 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.ActualEndDate().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 197 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.ActualEndDate().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n \t\t\t\t\t\t    <div class=\"divTdRight btnLu\" ");
            
            #line 198 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && task.IsRollUp().value == "1")? "style=display:none;" : ""));
            
            #line default
            #line hidden
            this.Write(">\r\n\t\t\t\t\t\t\t <span class=\"glyphicon glyphicon-calendar\"></span>\r\n\t\t\t\t\t\t    </div>\r\n" +
                    "                          </div>\r\n                        </div>\r\n              " +
                    "        </div>\r\n");
            
            #line 204 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
		for (int i=0;i<myDivMtCount;i++){ 
            
            #line default
            #line hidden
            this.Write("                       <div class=\"divTdMt\">&nbsp</div>\r\n");
            
            #line 206 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
		} 
            
            #line default
            #line hidden
            this.Write("                    </div>\r\n                  </div>\r\n                </div>\r\n   " +
                    "           </td>\r\n            </tr>\r\n");
            
            #line 212 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"

	    if (task.ChildTasks.Count>0)
        {
			uEachTask(task.ChildTasks,argLvlOrder+1,argTreeDepth,argIsMpp);
        }
	}
};
            
            #line default
            #line hidden
            
            #line 219 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"

Action<List<mpxWrapper.SnowProject>,int,bool>
uEachProject = null; // null to avoid compile-time error
uEachProject  = delegate(List<mpxWrapper.SnowProject> argProjList, int argTreeDepth, bool argIsMpp)
{
    foreach(mpxWrapper.SnowProject proj in argProjList)
    { 
            
            #line default
            #line hidden
            this.Write("<tr level=\"0\">\r\n    <td class=\"divBtnExpCol\" style=\"background:transparent;min-wi" +
                    "dth:14px;\">\r\n      <span class=\"glyphicon glyphicon-plus\"></span>\r\n    </td>\r\n  " +
                    "  <td colspan=\"");
            
            #line 230 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(argTreeDepth));
            
            #line default
            #line hidden
            this.Write(@""">
      <div class=""divTable mb"">
        <div class=""divThead"" >
          <div class=""divTr"">
            <div class=""divTh tdPortfolio"">Portfolio</div>
            <div class=""divTh tdProgram"">Program</div>
            <div class=""divTh tdConfigItem"">Configuration Item</div>");
            
            #line 236 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 if (!argIsMpp) { 
            
            #line default
            #line hidden
            this.Write("            <div class=\"divTh tdProjectNum\">Project</div>");
            
            #line 237 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            <div class=""divTh tdProjectName"">Name</div>
            <div class=""divTh tdProjectMgr"">Project Mgr</div>
            <div class=""divTh tdPhase_"">Phase</div>
            <div class=""divTh tdPhaseType"">Phase Type</div>
            <div class=""divTh tdSchedule"">Schedule</div>
            <div class=""divTh tdState"">State</div>
            <div class=""divTh tdPriority"">Priority</div>
            <div class=""divTh tdRisk"">Risk</div>
            <div class=""divTh tdStrategicPriority"">Strategic Priority</div>
            <div class=""divTh tdHotItem"">Hot Item</div>
            <div class=""divTh tdNeedsFollowUp"">Needs Follow Up</div>
            <div class=""divTh tdPlannedStartDate "">Planned Start Date</div>
            <div class=""divTh tdPlannedEndDate"">Planned End Date</div>
            <div class=""divTh tdActualStartDate"">Actual Start Date</div>
            <div class=""divTh tdActualEndDate"">Actual End Date</div>
            <div class=""divTdMt"">&nbsp</div>
            <div class=""divTdMt"">&nbsp</div>
          </div>
        </div>
        <div class=""divTbody"">
          <div class=""divTr"">
            <div class=""divTd bgWhite tdPortfolio"" status=""");
            
            #line 259 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Portfolio().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 262 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Portfolio().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 262 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Portfolio().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-search""></span>
                  </div>
                </div>
              </div>
            </div>
            <div class=""divTd bgWhite tdProgram"" status=""");
            
            #line 269 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Program().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 272 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Program().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 272 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Program().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-search""></span>
                  </div>
                </div>
              </div>
            </div>
            <div class=""divTd bgWhite tdConfigItem"" status=""");
            
            #line 279 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Cmdbci().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 282 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Cmdbci().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 282 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Cmdbci().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n                  <div class=\"divTdRight btnLu\">\r\n                    <sp" +
                    "an class=\"glyphicon glyphicon-search\"></span>\r\n                  </div>\r\n       " +
                    "         </div>\r\n              </div>\r\n            </div>");
            
            #line 288 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 if (!argIsMpp) { 
            
            #line default
            #line hidden
            this.Write("            <div class=\"divTd  bgWhite fieldReadOnly\" status=\"");
            
            #line 289 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ProjectNum().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n\t\t\t\t<div class=\"divTd\" style=\"border:none;\" value=\"");
            
            #line 290 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ProjectNum().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 290 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ProjectNum().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n\t\t\t</div>");
            
            #line 291 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t<div class=\"divTd bgWhite tdProjectName\" status=\"");
            
            #line 292 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ProjectName().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 295 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ProjectName().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 295 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ProjectName().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-edit""></span>
                  </div>
                </div>
              </div>
			</div>
            <div class=""divTd bgWhite tdProjectMgr"" status=""");
            
            #line 302 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ProjMgr().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 305 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ProjMgr().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 305 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ProjMgr().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-search""></span>
                  </div>
                </div>
              </div>
            </div>
            <div class=""divTd bgWhite tdPhase_"" status=""");
            
            #line 312 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Phase().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 315 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Phase().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 315 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Phase().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-search""></span>
                  </div>
                </div>
              </div>
            </div>
            <div class=""divTd bgWhite tdPhaseType"" status=""");
            
            #line 322 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.PhaseType().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 325 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.PhaseType().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 325 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.PhaseType().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-search""></span>
                  </div>
                </div>
              </div>
            </div>
            <div class=""divTd bgWhite tdSchedule"" status=""");
            
            #line 332 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Schedule().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 335 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Schedule().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 335 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Schedule().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-search""></span>
                  </div>
                </div>
              </div>
			</div>
            <div class=""divTd bgWhite tdState");
            
            #line 342 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && proj.IsRollUp().value == "1")? " fieldReadOnly" : ""));
            
            #line default
            #line hidden
            this.Write("\" status=\"");
            
            #line 342 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.State().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\" value=\"");
            
            #line 343 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.State().value));
            
            #line default
            #line hidden
            this.Write("\">\r\n                <div class=\"divTr\">\r\n                  <div class=\"divTd\">");
            
            #line 345 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.State().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n                  <div class=\"divTdRight btnLu\" ");
            
            #line 346 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && proj.IsRollUp().value == "1")? "style=display:none;" : ""));
            
            #line default
            #line hidden
            this.Write(">\r\n                    <span class=\"glyphicon glyphicon-search\"></span>\r\n        " +
                    "          </div>\r\n                </div>\r\n              </div>\r\n            </di" +
                    "v>\r\n            <div class=\"divTd bgWhite tdPriority\" status=\"");
            
            #line 352 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Priority().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 355 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Priority().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 355 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Priority().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-search""></span>
                  </div>
                </div>
              </div>
            </div>
            <div class=""divTd bgWhite tdRisk"" status=""");
            
            #line 362 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Risk().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 365 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Risk().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 365 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.Risk().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-search""></span>
                  </div>
                </div>
              </div>
            </div>
            <div class=""divTd bgWhite tdStrategicPriority"" status=""");
            
            #line 372 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.StrategicPriority().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 375 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.StrategicPriority().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 375 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.StrategicPriority().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-edit""></span>
                  </div>
                </div>
              </div>
			</div>
            <div class=""divTd bgWhite tdHotItem"" status=""");
            
            #line 382 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.HotItem().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 385 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.HotItem().value != ""? proj.HotItem().value : "0"));
            
            #line default
            #line hidden
            this.Write("\">\r\n");
            
            #line 386 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 if (proj.HotItem().value=="1") { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<span class=\"glyphicon glyphicon-ok\"></span>\r\n");
            
            #line 387 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<span class=\"glyphicon glyphicon-ban-circle\"></span>");
            
            #line 387 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 }; 
            
            #line default
            #line hidden
            this.Write(@"				  </div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-edit""></span>
                  </div>
                </div>
              </div>
			</div>
            <div class=""divTd bgWhite tdNeedsFollowUp"" status=""");
            
            #line 395 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.NeedsFollowUp().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr\">\r" +
                    "\n                  <div class=\"divTd\" value=\"");
            
            #line 398 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.NeedsFollowUp().value != ""? proj.NeedsFollowUp().value : "0"));
            
            #line default
            #line hidden
            this.Write("\">\r\n");
            
            #line 399 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 if (proj.NeedsFollowUp().value=="1") { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<span class=\"glyphicon glyphicon-ok\"></span>\r\n");
            
            #line 400 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<span class=\"glyphicon glyphicon-ban-circle\"></span>");
            
            #line 400 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 }; 
            
            #line default
            #line hidden
            this.Write(@"				  </div>
                  <div class=""divTdRight btnLu"">
                    <span class=""glyphicon glyphicon-edit""></span>
                  </div>
                </div>
              </div>
			</div>
            <div class=""divTd bgWhite tdPlannedStartDate"" status=""");
            
            #line 408 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.PlannedStartDate().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr dt" +
                    "mDiv\">\r\n                  <div class=\"divTd\" value=\"");
            
            #line 411 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.PlannedStartDate().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 411 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.PlannedStartDate().label));
            
            #line default
            #line hidden
            this.Write(@"</div>
                  <div class=""divTdRight btnCal"">
                      <span class=""glyphicon glyphicon-calendar""></span>
                  </div>
                </div>
              </div>
            </div>
            <div class=""divTd bgWhite tdPlannedEndDate");
            
            #line 418 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && proj.IsRollUp().value == "1")? " fieldReadOnly" : ""));
            
            #line default
            #line hidden
            this.Write("\" status=\"");
            
            #line 418 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.PlannedEndDate().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr dt" +
                    "mDiv\">\r\n                  <div class=\"divTd\" value=\"");
            
            #line 421 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.PlannedEndDate().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 421 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.PlannedEndDate().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n                  <div class=\"divTdRight btnLu\" ");
            
            #line 422 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && proj.IsRollUp().value == "1")?  "style=display:none;" : ""));
            
            #line default
            #line hidden
            this.Write(">\r\n                    <span class=\"glyphicon glyphicon-calendar\"></span>\r\n      " +
                    "            </div>\r\n                </div>\r\n              </div>\r\n            </" +
                    "div>\r\n            <div class=\"divTd bgWhite tdActualStartDate");
            
            #line 428 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && proj.IsRollUp().value == "1")? " fieldReadOnly" : ""));
            
            #line default
            #line hidden
            this.Write("\" status=\"");
            
            #line 428 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ActualStartDate().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr dt" +
                    "mDiv\">\r\n                  <div class=\"divTd\" value=\"");
            
            #line 431 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ActualStartDate().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 431 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ActualStartDate().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n                  <div class=\"divTdRight btnLu\" ");
            
            #line 432 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && proj.IsRollUp().value == "1")?  "style=display:none;" : ""));
            
            #line default
            #line hidden
            this.Write(">\r\n                    <span class=\"glyphicon glyphicon-calendar\"></span>\r\n      " +
                    "            </div>\r\n                </div>\r\n              </div>\r\n            </" +
                    "div>\r\n            <div class=\"divTd bgWhite tdActualEndDate");
            
            #line 438 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && proj.IsRollUp().value == "1")? " fieldReadOnly" : ""));
            
            #line default
            #line hidden
            this.Write("\" status=\"");
            
            #line 438 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ActualEndDate().datastatus));
            
            #line default
            #line hidden
            this.Write("\">\r\n              <div class=\"divTable mt\">\r\n                <div class=\"divTr dt" +
                    "mDiv\">\r\n                  <div class=\"divTd\" value=\"");
            
            #line 441 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ActualEndDate().value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 441 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proj.ActualEndDate().label));
            
            #line default
            #line hidden
            this.Write("</div>\r\n                  <div class=\"divTdRight btnLu\" ");
            
            #line 442 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((!argIsMpp && proj.IsRollUp().value == "1")?  "style=display:none;" : ""));
            
            #line default
            #line hidden
            this.Write(@">
                    <span class=""glyphicon glyphicon-calendar""></span>
                  </div>
                </div>
              </div>
            </div>
            <div class=""divTdMt"">&nbsp</div>
            <div class=""divTdMt"">&nbsp</div>
          </div>
        </div>
      </div>
    </td>
  </tr>
  ");
            
            #line 455 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"

		if (proj.ChildTasks.Count>0)
		{
			uEachTask(proj.ChildTasks,1,argTreeDepth,argIsMpp);
		}
	}
};
            
            #line default
            #line hidden
            this.Write("<!doctype html>\r\n<html>\r\n<head>\r\n<meta charset=\"utf-8\">\r\n<title>Snow Mpp</title>\r" +
                    "\n<link rel=\"icon\" href=\"../images/favicon.ico\" type=\"image/x-icon\" />\r\n<link rel" +
                    "=\"stylesheet\" type=\"text/css\" href=\"../styles/mySite");
            
            #line 468 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(twpIsMpp?"":"2"));
            
            #line default
            #line hidden
            this.Write(@".css"">
<link rel=""stylesheet"" href=""https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"">
<link rel=""stylesheet"" href=""https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"">
<script type=""text/javascript"" src=""https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js""></script>
<script type=""text/javascript"" src=""https://code.jquery.com/ui/1.12.1/jquery-ui.min.js""></script>
<script type=""text/javascript"" src=""https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js""></script>
<script type=""text/javascript"" src=""../scripts/ejs2.min.js""></script>
<script type=""text/javascript"" src=""../tmpscript/myludata.js""></script>
<script type=""text/javascript"" src=""../scripts/jquery.myUtilPlugin.js""></script>
</head>
<body>
<div class=""container"">
<table style=""border-collapse: collapse;"">
");
            
            #line 481 "C:\_myMppStuff\utaSnowMpp4\myMpxjLib\Templates\templateWebPage.tt"
 uEachProject(twpProject,twpDepth,twpIsMpp); 
            
            #line default
            #line hidden
            this.Write("</table>\r\n</div>\r\n<div id=\"divDatePickerContainer\" style=\"display:none;border-top" +
                    ":8px solid #999;width:fit-content;\" on>\r\n\t<table><tr>\r\n\t\t<td><input id=\"inpDp\" t" +
                    "ype=\"text\" value=\"YYYY-MM-DD\" style=\"width:138px;background:#ddd;\" readonly/></t" +
                    "d>\r\n\t\t<td><input id=\"inpTime\" type=\"time\" value=\"\"/></td>\t\t\r\n\t</tr>\r\n\t<tr id=\"tr" +
                    "FinalCalBtnRow\" style=\"display:none;\">\r\n\t\t<td colspan=\"2\" style=\"text-align:righ" +
                    "t;align-content:right;padding-top:2px;\">\r\n\t\t\t<div id=\"divBtnCalAccept\" class=\"bt" +
                    "nGlyph\">\r\n\t\t\t\t<span class=\"glyphicon glyphicon-ok\" style=\"font-size:14px;vertica" +
                    "l-align:top;\">\r\n\t\t\t</div>\r\n\t\t\t<div id=\"divBtnCalReject\" class=\"btnGlyph\">\r\n\t\t\t\t<" +
                    "span class=\"glyphicon glyphicon-remove\" style=\"font-size:14px;vertical-align:top" +
                    ";margin-top:1px;\"></span></td>\r\n\t\t\t</div>\r\n\t\t</td>\r\n\t</tr>\r\n\t</table>\r\n\t<div id=" +
                    "\"divDatePicker\"></div>\r\n\t<div id=\"divBtnDpExitContainer\" style=\"display:block;wi" +
                    "dth:100%;text-align:right;align-content:right;background-color:#eee;\">&nbsp;\r\n\t\t" +
                    "<div class=\"btnDpContainer\">\r\n\t\t\t<div id=\"divBtnDpTimeUpd\" class=\"btnDp\" style=\"" +
                    "display:none;\">Time Update</div>\r\n\t\t\t<div id=\"divBtnDpEmpty\" class=\"btnDp\" >Clea" +
                    "r Date</div>\r\n\t\t\t<div id=\"divBtnDpExit\" class=\"btnDp\">Exit</div>\r\n\t\t</div>\r\n\t</d" +
                    "iv>\r\n</div>\r\n<div id=\"divLuContainer\" style=\"display:none;border:1px solid black" +
                    ";background:#eee;width:fit-content;\">\r\n    <div id=\"divBtnLuExit\" class=\"btn2Gly" +
                    "ph\" style=\"float:right;padding:0px 0px 0px 0px;\"><span class=\"glyphicon glyphico" +
                    "n-remove\" style=\"font-size:12px;vertical-align:top;margin-top:1px;\"></div>\r\n\t<di" +
                    "v style=\"display:block;padding:12px\">\r\n\t\t<table id=\"tblLu\" class=\"lu\" value=\"1\">" +
                    "\r\n\t\t</table>\r\n\t</div>\r\n</div>\r\n</body>\r\n\t<script type=\"text/javascript\">\r\n\t\t$(wi" +
                    "ndow).on(\'load\',function()\r\n\t\t{\r\n\t\t\t$($.myBtnLuClass).click($().myUtilPlugin().l" +
                    "uClick);\t\r\n\t\t\t$($.myBtnCalClass).click($().myUtilPlugin().calClick);\t\r\n\t\t\t$($.my" +
                    "BtnCalAcceptId).click($().myUtilPlugin().calAccept);\t\r\n\t\t\t$($.myBtnCalRejectId)." +
                    "click($().myUtilPlugin().calReject);\t\r\n\t\t\t$($.myBtnDpExitId).click($().myUtilPlu" +
                    "gin().calClose);\r\n\t\t\t$($.myBtnDpTimeUpdId).click($().myUtilPlugin().calSelectTim" +
                    "eUpd);\t\t\t\r\n\t\t\t$($.myBtnDpEmtpyId).click($().myUtilPlugin().calBlank);\t\t\t\r\n\t\t\t$($" +
                    ".myBtnLuExitId).click($().myUtilPlugin().luExit);\r\n\t\t\t$($.myDivDatePickerContain" +
                    "erId).click($().myUtilPlugin().ehIgnore);\r\n\t\t\t$($.myDivLuContainerId).click($()." +
                    "myUtilPlugin().ehIgnore);\r\n\t\t\t$(window).bind(\'mousewheel\',$().myUtilPlugin().ehW" +
                    "indow);\r\n\t\t\t$(window).click($().myUtilPlugin().ehWindow);\r\n\t\t\t$().myUtilPlugin()" +
                    ".ecInitTr();\r\n\t\t});\t\t\r\n\t</script>\r\n</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class templateWebPageBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
